import {SlashCommandBuilder,PermissionFlagsBits,ChannelType,EmbedBuilder} from "discord.js";
import {getSettings,updateSettings,getUser,addXp,addCoins,claimDaily,activityLeaderboard,xpLeaderboard,addWarning,getWarnings,addReport,addSuggestion,addReminder,addServerNote,getServerNotes,getOpenReports,setReportStatus} from "./database.js";
import {embed,success,errorEmbed,formatDuration,parseDuration} from "./utils.js";

const c=[];const add=x=>c.push(x);
add(new SlashCommandBuilder().setName("help").setDescription("Show all Ultra Tag Assistant features."));
add(new SlashCommandBuilder().setName("ping").setDescription("Check latency."));
add(new SlashCommandBuilder().setName("botinfo").setDescription("Show bot information."));
add(new SlashCommandBuilder().setName("server").setDescription("Show server information."));
add(new SlashCommandBuilder().setName("userinfo").setDescription("Show member information.").addUserOption(o=>o.setName("user").setDescription("Member")));
add(new SlashCommandBuilder().setName("avatar").setDescription("Show an avatar.").addUserOption(o=>o.setName("user").setDescription("Member")));
add(new SlashCommandBuilder().setName("profile").setDescription("Show a community profile.").addUserOption(o=>o.setName("user").setDescription("Member")));
add(new SlashCommandBuilder().setName("rank").setDescription("Show XP leaderboard."));
add(new SlashCommandBuilder().setName("leaderboard").setDescription("Show activity leaderboard."));
add(new SlashCommandBuilder().setName("activity").setDescription("Show your activity statistics."));
add(new SlashCommandBuilder().setName("activity-test").setDescription("Preview the activity-check embed."));
add(new SlashCommandBuilder().setName("daily").setDescription("Claim 50 daily coins."));
add(new SlashCommandBuilder().setName("streak").setDescription("Show your activity streak."));
add(new SlashCommandBuilder().setName("suggest").setDescription("Submit a suggestion.").addStringOption(o=>o.setName("idea").setDescription("Suggestion").setRequired(true).setMaxLength(1000)));
add(new SlashCommandBuilder().setName("report").setDescription("Report a player or issue.").addStringOption(o=>o.setName("details").setDescription("Details").setRequired(true).setMaxLength(1500)).addStringOption(o=>o.setName("type").setDescription("Type").addChoices({name:"Player",value:"player"},{name:"Bug",value:"bug"},{name:"Discord",value:"discord"},{name:"Other",value:"other"})).addUserOption(o=>o.setName("user").setDescription("Reported member")));
add(new SlashCommandBuilder().setName("remind").setDescription("Create a reminder.").addStringOption(o=>o.setName("when").setDescription("10m, 2h, 1d").setRequired(true)).addStringOption(o=>o.setName("message").setDescription("Reminder").setRequired(true).setMaxLength(500)));
add(new SlashCommandBuilder().setName("8ball").setDescription("Ask the Ultra Tag 8-ball.").addStringOption(o=>o.setName("question").setDescription("Question").setRequired(true)));
add(new SlashCommandBuilder().setName("coinflip").setDescription("Flip a coin."));
add(new SlashCommandBuilder().setName("roll").setDescription("Roll a dice.").addIntegerOption(o=>o.setName("sides").setDescription("2-100").setMinValue(2).setMaxValue(100)));
add(new SlashCommandBuilder().setName("set-activity-channel").setDescription("Set the activity channel.").addChannelOption(o=>o.setName("channel").setDescription("Text channel").addChannelTypes(ChannelType.GuildText).setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild));
add(new SlashCommandBuilder().setName("set-log-channel").setDescription("Set the log channel.").addChannelOption(o=>o.setName("channel").setDescription("Text channel").addChannelTypes(ChannelType.GuildText).setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild));
add(new SlashCommandBuilder().setName("activity-config").setDescription("Configure activity checks.").addBooleanOption(o=>o.setName("enabled").setDescription("Enabled")).addIntegerOption(o=>o.setName("hour").setDescription("Dublin hour").setMinValue(0).setMaxValue(23)).addIntegerOption(o=>o.setName("minute").setDescription("Minute").setMinValue(0).setMaxValue(59)).addStringOption(o=>o.setName("emoji").setDescription("Reaction")).addIntegerOption(o=>o.setName("required").setDescription("Required checks").setMinValue(1).setMaxValue(1000)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild));
add(new SlashCommandBuilder().setName("warn").setDescription("Warn a member.").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason").setRequired(true).setMaxLength(500)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers));
add(new SlashCommandBuilder().setName("warnings").setDescription("View warnings.").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers));
add(new SlashCommandBuilder().setName("timeout").setDescription("Timeout a member.").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("duration").setDescription("10m, 2h, 1d").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason")).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers));
add(new SlashCommandBuilder().setName("kick").setDescription("Kick a member.").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason")).setDefaultMemberPermissions(PermissionFlagsBits.KickMembers));
add(new SlashCommandBuilder().setName("ban").setDescription("Ban a member.").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason")).setDefaultMemberPermissions(PermissionFlagsBits.BanMembers));
add(new SlashCommandBuilder().setName("clear").setDescription("Delete messages.").addIntegerOption(o=>o.setName("amount").setDescription("1-100").setMinValue(1).setMaxValue(100).setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages));
add(new SlashCommandBuilder().setName("slowmode").setDescription("Set channel slowmode.").addIntegerOption(o=>o.setName("seconds").setDescription("0-21600").setMinValue(0).setMaxValue(21600).setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels));
add(new SlashCommandBuilder().setName("lock").setDescription("Lock current channel.").setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels));
add(new SlashCommandBuilder().setName("unlock").setDescription("Unlock current channel.").setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels));
add(new SlashCommandBuilder().setName("note").setDescription("Add a private staff note.").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("note").setDescription("Note").setRequired(true).setMaxLength(1000)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers));
add(new SlashCommandBuilder().setName("notes").setDescription("View staff notes.").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers));
add(new SlashCommandBuilder().setName("reports").setDescription("View open reports.").setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers));
add(new SlashCommandBuilder().setName("report-close").setDescription("Close a report.").addIntegerOption(o=>o.setName("id").setDescription("Report ID").setMinValue(1).setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers));
add(new SlashCommandBuilder().setName("poll").setDescription("Create a poll.").addStringOption(o=>o.setName("question").setDescription("Question").setRequired(true)).addStringOption(o=>o.setName("option1").setDescription("Option 1").setRequired(true)).addStringOption(o=>o.setName("option2").setDescription("Option 2").setRequired(true)).addStringOption(o=>o.setName("option3").setDescription("Option 3")).addStringOption(o=>o.setName("option4").setDescription("Option 4")).setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages));
add(new SlashCommandBuilder().setName("announce").setDescription("Send a branded announcement.").addChannelOption(o=>o.setName("channel").setDescription("Destination").addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName("title").setDescription("Title").setRequired(true)).addStringOption(o=>o.setName("message").setDescription("Message").setRequired(true).setMaxLength(4000)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild));
add(new SlashCommandBuilder().setName("giveaway").setDescription("Start a reaction giveaway.").addIntegerOption(o=>o.setName("minutes").setDescription("Duration").setMinValue(1).setMaxValue(10080).setRequired(true)).addStringOption(o=>o.setName("prize").setDescription("Prize").setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild));
add(new SlashCommandBuilder().setName("verify").setDescription("Self-assign the configured verified role."));
add(new SlashCommandBuilder().setName("status").setDescription("Show bot status."));
export const commands=c;

export async function handleCommand(i,client){
  const n=i.commandName,g=i.guild;
  if(!g&&n!=="ping"&&n!=="botinfo")return i.reply({content:"This command must be used in a server.",ephemeral:true});
  try{
    if(n==="help")return i.reply({embeds:[embed("🏷️ Ultra Tag Assistant","**Community:** /profile /activity /leaderboard /rank /daily /streak /suggest /report /remind\n\n**Utilities:** /ping /botinfo /server /userinfo /avatar /8ball /coinflip /roll /status /verify\n\n**Setup:** /set-activity-channel /set-log-channel /activity-config /activity-test\n\n**Moderation:** /warn /warnings /timeout /kick /ban /clear /slowmode /lock /unlock\n\n**Staff:** /note /notes /reports /report-close /announce /poll /giveaway")],ephemeral:true});
    if(n==="ping")return i.reply({embeds:[success("Pong","Gateway: "+client.ws.ping+"ms")]});
    if(n==="botinfo")return i.reply({embeds:[embed("🏷️ Ultra Tag Assistant","Official Discord bot for Ultra Tag.").addFields({name:"Servers",value:String(client.guilds.cache.size),inline:true},{name:"Commands",value:String(commands.length),inline:true},{name:"Uptime",value:formatDuration(client.uptime),inline:true})]});
    if(n==="server")return i.reply({embeds:[embed("🏷️ "+g.name,"Owner: <@"+g.ownerId+">\nMembers: "+g.memberCount+"\nChannels: "+g.channels.cache.size+"\nCreated: <t:"+Math.floor(g.createdTimestamp/1000)+":D>")]});
    if(n==="userinfo"){const u=i.options.getUser("user")||i.user,m=await g.members.fetch(u.id).catch(()=>null);return i.reply({embeds:[embed("👤 "+u.username,"ID: "+u.id+"\nJoined: "+(m?"<t:"+Math.floor(m.joinedTimestamp/1000)+":R>":"Unknown")+"\nCreated: <t:"+Math.floor(u.createdTimestamp/1000)+":R>")]});}
    if(n==="avatar"){const u=i.options.getUser("user")||i.user;return i.reply({embeds:[new EmbedBuilder().setTitle(u.username+"'s Avatar").setImage(u.displayAvatarURL({size:1024})).setColor(0x5865F2)]});}
    if(n==="profile"){const u=i.options.getUser("user")||i.user,p=getUser(g.id,u.id);return i.reply({embeds:[embed("🏷️ "+u.username+"'s Profile","").addFields({name:"Level",value:String(p.level),inline:true},{name:"XP",value:String(p.xp),inline:true},{name:"Coins",value:String(p.coins),inline:true},{name:"Activity",value:String(p.total_activity),inline:true},{name:"Streak",value:p.streak+" days",inline:true},{name:"Messages",value:String(p.messages),inline:true})]});}
    if(n==="rank"){const r=xpLeaderboard(g.id);return i.reply({embeds:[embed("🏆 XP Leaderboard",r.length?r.map((x,k)=>"**"+(k+1)+".** <@"+x.user_id+"> — Level "+x.level+" • "+x.xp+" XP • "+x.coins+" coins").join("\n"):"No XP data yet.")]});}
    if(n==="leaderboard"){const r=activityLeaderboard(g.id);return i.reply({embeds:[embed("📊 Activity Leaderboard",r.length?r.map((x,k)=>"**"+(k+1)+".** <@"+x.user_id+"> — "+x.total_activity+" checks • "+x.streak+" streak").join("\n"):"No activity data yet.")]});}
    if(n==="activity"){const p=getUser(g.id,i.user.id);return i.reply({embeds:[embed("📊 Your Activity","Checks: **"+p.total_activity+"**\nStreak: **"+p.streak+" days**\nLast check: **"+(p.last_activity||"Never")+"**\nXP: **"+p.xp+"**\nCoins: **"+p.coins+"**")],ephemeral:true});}
    if(n==="activity-test"){const s=getSettings(g.id);return i.reply({embeds:[embed("🏷️ Ultra Tag — Daily Activity Check","**Daily activity check is now open.**\n\n"+s.activity_emoji+" React to this message to mark yourself active today.\nYou earn **25 XP + 10 coins** for checking in.").addFields({name:"Schedule",value:String(s.activity_hour).padStart(2,"0")+":"+String(s.activity_minute).padStart(2,"0")+" Europe/Dublin",inline:true},{name:"Reaction",value:s.activity_emoji,inline:true})]});}
    if(n==="daily"){const day=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Dublin",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());if(!claimDaily(g.id,i.user.id,day))return i.reply({embeds:[errorEmbed("You already claimed today's reward.")],ephemeral:true});return i.reply({embeds:[success("Daily claimed","You received **50 coins + 10 XP**.")],ephemeral:true});}
    if(n==="streak")return i.reply({embeds:[embed("🔥 Activity Streak","Your current streak is **"+getUser(g.id,i.user.id).streak+" day(s)**.")]});
    if(n==="suggest"){const id=addSuggestion(g.id,i.user.id,i.options.getString("idea",true));return i.reply({embeds:[success("Suggestion submitted","Suggestion #"+id+" has been recorded.")],ephemeral:true});}
    if(n==="report"){const id=addReport(g.id,i.user.id,i.options.getUser("user")?.id,i.options.getString("type")||"other",i.options.getString("details",true));return i.reply({embeds:[success("Report submitted","Report #"+id+" has been sent to staff.")],ephemeral:true});}
    if(n==="remind"){const d=parseDuration(i.options.getString("when",true));if(!d)return i.reply({embeds:[errorEmbed("Use 10m, 2h, 1d or 1w.")],ephemeral:true});const id=addReminder(g.id,i.user.id,i.channelId,i.options.getString("message",true),Date.now()+d);return i.reply({embeds:[success("Reminder created","Reminder #"+id+" fires <t:"+Math.floor((Date.now()+d)/1000)+":R>.")],ephemeral:true});}
    if(n==="8ball"){const a=["Yes.","No.","Probably.","Probably not.","Ask again later.","Absolutely.","Unclear.","The Ultra Tag servers say yes."];return i.reply({embeds:[embed("🎱 Ultra Tag 8-Ball",a[Math.floor(Math.random()*a.length)])]});}
    if(n==="coinflip")return i.reply({embeds:[embed("🪙 Coin Flip",Math.random()<.5?"Heads.":"Tails.")]});
    if(n==="roll"){const s=i.options.getInteger("sides")||6;return i.reply({embeds:[embed("🎲 Dice Roll","You rolled **"+(Math.floor(Math.random()*s)+1)+"** on a d"+s+".")]});}
    if(n==="set-activity-channel"){const c=i.options.getChannel("channel",true);updateSettings(g.id,{activity_channel_id:c.id});return i.reply({embeds:[success("Activity channel updated","Daily checks will post in <#"+c.id+">.")],ephemeral:true});}
    if(n==="set-log-channel"){const c=i.options.getChannel("channel",true);updateSettings(g.id,{log_channel_id:c.id});return i.reply({embeds:[success("Log channel updated","Logs will use <#"+c.id+">.")],ephemeral:true});}
    if(n==="activity-config"){const patch={};for(const [o,k] of [["enabled","activity_enabled"],["hour","activity_hour"],["minute","activity_minute"],["emoji","activity_emoji"],["required","activity_required"]]){const x=i.options.get(o);if(x!==null)patch[k]=x.value;}const s=updateSettings(g.id,patch);return i.reply({embeds:[success("Activity configuration saved","Enabled: **"+Boolean(s.activity_enabled)+"**\nTime: **"+String(s.activity_hour).padStart(2,"0")+":"+String(s.activity_minute).padStart(2,"0")+" Europe/Dublin**\nReaction: **"+s.activity_emoji+"**\nRequired: **"+s.activity_required+"**")],ephemeral:true});}
    if(n==="warn"){const u=i.options.getUser("user",true),id=addWarning(g.id,u.id,i.user.id,i.options.getString("reason",true));return i.reply({embeds:[success("Warning issued","<@"+u.id+"> received warning #"+id+".")]});}
    if(n==="warnings"){const u=i.options.getUser("user",true),r=getWarnings(g.id,u.id);return i.reply({embeds:[embed("⚠️ Warnings — "+u.username,r.length?r.map(x=>"#"+x.id+" • <t:"+Math.floor(x.created_at/1000)+":d> • <@"+x.moderator_id+">\n"+x.reason).join("\n\n"):"No warnings recorded.")]});}
    if(n==="timeout"){const u=i.options.getUser("user",true),d=parseDuration(i.options.getString("duration",true));if(!d||d>2419200000)return i.reply({embeds:[errorEmbed("Use a duration up to 28 days.")],ephemeral:true});await (await g.members.fetch(u.id)).timeout(d,i.options.getString("reason")||"No reason provided");return i.reply({embeds:[success("Member timed out","<@"+u.id+"> for **"+formatDuration(d)+"**.")]});}
    if(n==="kick"){const u=i.options.getUser("user",true);await (await g.members.fetch(u.id)).kick(i.options.getString("reason")||"No reason provided");return i.reply({embeds:[success("Member kicked","<@"+u.id+"> was kicked.")]});}
    if(n==="ban"){const u=i.options.getUser("user",true);await g.members.ban(u.id,{reason:i.options.getString("reason")||"No reason provided"});return i.reply({embeds:[success("Member banned","<@"+u.id+"> was banned.")]});}
    if(n==="clear"){const a=i.options.getInteger("amount",true),d=await i.channel.bulkDelete(a,true);return i.reply({embeds:[success("Messages cleared","Deleted **"+d.size+"** messages.")],ephemeral:true});}
    if(n==="slowmode"){const s=i.options.getInteger("seconds",true);await i.channel.setRateLimitPerUser(s);return i.reply({embeds:[success("Slowmode updated",s?"Slowmode is **"+s+"s**.":"Slowmode disabled.")]});}
    if(n==="lock"){await i.channel.permissionOverwrites.edit(g.roles.everyone,{SendMessages:false});return i.reply({embeds:[success("Channel locked","Members can no longer send messages here.")]});}
    if(n==="unlock"){await i.channel.permissionOverwrites.edit(g.roles.everyone,{SendMessages:null});return i.reply({embeds:[success("Channel unlocked","Member message permissions restored.")]});}
    if(n==="note"){const u=i.options.getUser("user",true),id=addServerNote(g.id,u.id,i.user.id,i.options.getString("note",true));return i.reply({embeds:[success("Staff note saved","Private note #"+id+" saved.")],ephemeral:true});}
    if(n==="notes"){const u=i.options.getUser("user",true),r=getServerNotes(g.id,u.id);return i.reply({embeds:[embed("📝 Staff Notes — "+u.username,r.length?r.map(x=>"#"+x.id+" • <t:"+Math.floor(x.created_at/1000)+":d> • <@"+x.moderator_id+">\n"+x.note).join("\n\n"):"No notes recorded.")],ephemeral:true});}
    if(n==="reports"){const r=getOpenReports(g.id);return i.reply({embeds:[embed("🚨 Open Reports",r.length?r.map(x=>"#"+x.id+" • "+x.type+" • <@"+x.reporter_id+"> "+(x.target_id?"→ <@"+x.target_id+">":"")+"\n"+x.details).join("\n\n"):"No open reports.")],ephemeral:true});}
    if(n==="report-close"){const id=i.options.getInteger("id",true);setReportStatus(g.id,id,"closed");return i.reply({embeds:[success("Report closed","Report #"+id+" is closed.")],ephemeral:true});}
    if(n==="poll"){const q=i.options.getString("question",true),opts=[1,2,3,4].map(x=>i.options.getString("option"+x)).filter(Boolean),letters=["🇦","🇧","🇨","🇩"],msg=await i.channel.send({embeds:[embed("📊 "+q,opts.map((x,k)=>letters[k]+" "+x).join("\n"))]});for(let k=0;k<opts.length;k++)await msg.react(letters[k]);return i.reply({content:"Poll created: "+msg.url,ephemeral:true});}
    if(n==="announce"){const ch=i.options.getChannel("channel",true),e=new EmbedBuilder().setTitle(i.options.getString("title",true)).setDescription(i.options.getString("message",true)).setColor(0x5865F2).setFooter({text:"Ultra Tag • Official Announcement"}).setTimestamp();await ch.send({content:"📢 **Ultra Tag Announcement**",embeds:[e]});return i.reply({embeds:[success("Announcement sent","Posted in <#"+ch.id+">.")],ephemeral:true});}
    if(n==="giveaway"){const minutes=i.options.getInteger("minutes",true),prize=i.options.getString("prize",true),end=Date.now()+minutes*60000,msg=await i.channel.send({embeds:[embed("🎉 Ultra Tag Giveaway","Prize: **"+prize+"**\n\nReact with 🎉 to enter.\nEnds <t:"+Math.floor(end/1000)+":R>")]});await msg.react("🎉");setTimeout(async()=>{try{const m=await msg.fetch(),r=m.reactions.cache.get("🎉"),u=r?await r.users.fetch():new Map(),eligible=[...u.values()].filter(x=>!x.bot),w=eligible[Math.floor(Math.random()*eligible.length)];await i.channel.send(w?"🎉 Congratulations <@"+w.id+">! You won **"+prize+"**.":"🎉 Giveaway ended with no eligible entries.");}catch(e){console.error("[giveaway]",e)}},minutes*60000);return i.reply({embeds:[success("Giveaway started","Prize: **"+prize+"** for **"+minutes+" minute(s)**.")],ephemeral:true});}
    if(n==="verify"){const roleId=getSettings(g.id)?.welcome_role_id;if(!roleId)return i.reply({embeds:[errorEmbed("No verified role is configured.")],ephemeral:true});const role=g.roles.cache.get(roleId);if(!role)return i.reply({embeds:[errorEmbed("Configured role no longer exists.")],ephemeral:true});await g.members.fetch(i.user.id).then(m=>m.roles.add(role));return i.reply({embeds:[success("Verified","You now have **"+role.name+"**.")],ephemeral:true});}
    if(n==="status")return i.reply({embeds:[embed("🟢 Ultra Tag Assistant Status","Connection: **"+(client.ws.status===0?"Connected":"Reconnecting")+"**\nLatency: **"+client.ws.ping+"ms**\nUptime: **"+formatDuration(client.uptime)+"**\nServers: **"+client.guilds.cache.size+"**")]});
  }catch(e){console.error("[command:"+n+"]",e);const p={embeds:[errorEmbed("The command could not be completed. Check bot permissions and inputs.")],ephemeral:true};return i.replied||i.deferred?i.followUp(p):i.reply(p);}
}
